[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=22.4",
    "requests>=2.32.5",
    "schedule>=1.2.2",
]
